Dessia-tech/dessia_common

dessia_common/workflow.py, setup.py
=> Dev new display

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/vectored_objects.py, dessia_common/workflow.py
`_display_angular` is now called `_displays`
`ParallelPlot is now renamed MultiPlot`
=> Display object

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/typings.py, dessia_common/vectored_objects.py, dessia_common/workflow.py, setup.py
=> Dev to master: towards version 0.4.2

dessia_common/core.py, dessia_common/workflow.py, setup.py
=> Workflow canvas

dessia_common/core.py, dessia_common/workflow.py
=> Serialize tuples

dessia_common/core.py, dessia_common/workflow.py, setup.py
=> Towards v0.4.2

CHANGELOG.md, dessia_common/core.py, dessia_common/scripts/unit_tests.py, dessia_common/workflow.py
=> Fix dict_to_arguments for Workflow/WorkflowRun

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/scripts/unit_tests.py, dessia_common/workflow.py, setup.py
Implements one typing of distance
Add some development features to forms (for workflow)
use get_type_hints instead of annotations
=> Towards043

CHANGELOG.md, dessia_common/forms.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/workflow.py
=> Typings debugs

dessia_common/core.py, dessia_common/forms.py
=> refactor: default_values

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/unit_tests.py
=> Jsonschema description

dessia_common/core.py, dessia_common/workflow.py
=> Type datatype

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/unit_tests.py
=> Default values

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/forms_script.py, dessia_common/scripts/unit_tests.py, dessia_common/typings.py, dessia_common/workflow.py
=> Rename Subclass as InstanceOf

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/forms_script.py, dessia_common/scripts/unit_tests.py, dessia_common/typings.py, dessia_common/workflow.py
=> Towards 0.4.4

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py
=> Serialize Dict typing

CHANGELOG.md, dessia_common/workflow.py
=> Fix Workflow eq & hash

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/workflow.py
Add Name setting when running workflow 
Add missing field to jsonschemas : #60
=> Workflow Enhancements

dessia_common/workflow.py
=> fix(workflow): add name argument to run_again

dessia_common/core.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/typings.py, dessia_common/workflow.py
=> Method typing

dessia_common/core.py
=> Remove mardown indents inside DisplayObject

dessia_common/core.py
=> feat(typing): redo MethodType serializing

dessia_common/workflow.py
=> feat(workflow): add kwargs to block Display subcall

dessia_common/workflow.py
=> fix(display_block): fix kwargs propagation

dessia_common/forms.py, dessia_common/scripts/unit_tests.py
=> feat(dev-objects): add non editable fields for dev purpose

CHANGELOG.md
=> docs(changelog): update

dessia_common/forms.py, dessia_common/scripts/unit_tests.py
=> xfeat(dev): add array_arg

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py
=> 89 support iterator

CHANGELOG.md, dessia_common/core.py, dessia_common/scripts/forms_script.py
=> feat: add object_class to DessiaObject's default dicts

dessia_common/core.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/workflow.py
=> Bug def dict workflow

dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/unit_tests.py
Add Tuple deserialization when available
Hash for tuples and lists are equal when cotnents are equals (not eq)
=> Tuple deserialization + has

dessia_common/core.py
=> fix(deserialiazition): protect missing key in annotations

dessia_common/forms.py
=> docs(forms): update forms header

dessia_common/optimization.py
Sometimes "Powell' resolution method is more efficient than default method.
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html)
=> allow user to choose the resolution method of scipy.optimize.minimize in InstantiatingModelOptimizer

CHANGELOG.md, dessia_common/workflow.py
=> Workflow Method blocks enhancements

dessia_common/workflow.py, tests/workflow/power_simulation.py
=> feat: workflow restart enhancements

dessia_common/workflow.py, tests/workflow/power_simulation.py
Implement a specific dict_to_object for WorkflowState
Fix: blocks -> pipes for activated_items computation in to_dict
Add activated_items to non_serializable_attributes
=> WorkflowState dict_to_object

CHANGELOG.md, dessia_common/workflow.py
=> Workflow restart

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/scripts/generate_from_file.py, dessia_common/tests.py, dessia_common/typings.py, dessia_common/workflow.py, tests/unit_tests.py
- New dev objects
- ClassMethodType
- Dirty : add classes to workflows method_jsonschemas in order to check for it frontend side while evaluating "run"
- Workflow method_dict gives {}
=> Miscellaneous changes

dessia_common/core.py, dessia_common/workflow.py
Partial implementation of Any type
=> featfix: add any type deserialisation and fix non-subclass test

dessia_common/graph.py
Graph perfo for dict_to_object debug
=> perf: graph exploration

CHANGELOG.md, code_quality.sh, dessia_common/core.py, dessia_common/workflow.py
=> Workflow Documentation & Description

code_quality.sh, dessia_common/files.py, dessia_common/utils/copy.py, dessia_common/utils/serialization.py
=> Feat save files

dessia_common/core.py
=> fix:  module dessia_common has no attribute serialize

dessia_common/workflow.py
=> fix(workflow): use append instead of extend

dessia_common/files.py
=> fix: copy for files error

dessia_common/utils/serialization.py
=> fix: files should not be serialized

dessia_common/utils/serialization.py
=> fix : files are not json serializable

code_pylint.py, dessia_common/breakdown.py, dessia_common/errors.py, dessia_common/utils/diff.py, dessia_common/utils/serialization.py, setup.py
=> fix: version number with commit hash, docs

.pylintrc, code_pylint.py, code_quality.sh, dessia_common/breakdown.py, dessia_common/core.py, dessia_common/displays.py, dessia_common/errors.py, dessia_common/exports.py, dessia_common/files.py, doc/source/customizing.rst, tests/ci_tests.py, tests/files.py
Template generation from filetypes
=> feat: template generation in file

.pydocstylerc, .pylintrc, code_pylint.py, code_quality.sh, dessia_common/core.py, dessia_common/displays.py, dessia_common/exports.py, dessia_common/templates.py, dessia_common/utils/algebra.py, dessia_common/utils/copy.py, dessia_common/utils/interpolation.py, dessia_common/utils/serialization.py, dessia_common/workflow.py
Split display generation by the means of display settings
=> feat: display settings

dessia_common/workflow.py
=> Feat/force default input : Add imposed_variable_indices handling

dessia_common/workflow.py
=> fix(workflow): fix method_jsonschema of run_again computation

dessia_common/core.py
=> return displays

dessia_common/breakdown.py, tests/workflow/power_simulation.py
Fix pb of getting with dict key beeing tuples
=> fix: get in object didn't handle tuple as dict keys

code_pylint.py, dessia_common/workflow/core.py
=> ci: better pylint script

code_pylint.py, dessia_common/core.py, dessia_common/forms.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> fiw(displays): set cad method name instead of None

code_pylint.py, dessia_common/utils/serialization.py, dessia_common/utils/types.py
Removing evals by ast literal evals (safer)
=> refactor: replace eval by ast literal evals

CHANGELOG.md, dessia_common/utils/jsonschema.py
=> fix(jsonschema): Typing Any does not raise error with subclass anymore

dessia_common/workflow/core.py
serialization of workflowrun: pb of serialization of variable values
=> fix: serialization of workflow run

dessia_common/core.py, dessia_common/utils/serialization.py, pre-commit
Semi custom dict to object had problems with path not transfered
=> fix: path not injected on forced generic dto

dessia_common/forms.py, dessia_common/utils/serialization.py, dessia_common/workflow/core.py
=> fix: deserialisation of file

dessia_common/workflow/core.py
=> fix(workflow): look for blocks in workflow instead of WorkflowRun

code_pylint.py, dessia_common/core.py, dessia_common/displays.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> Patch for Workflow Run Displays

dessia_common/workflow/core.py
Waiting for deeper changes on workflow jsonschemas (use of generic behavior), hotfixing this for frontend expected behavior
=> Fix : workflow jsonschemas

dessia_common/workflow/core.py
=> UNTESTED : fix variable copy

code_pylint.py, dessia_common/utils/jsonschema.py, dessia_common/utils/serialization.py
=> fix: handle all valid files subclasses

dessia_common/templates.py, dessia_common/utils/serialization.py
Handle subclass of dessia files
=> fix: handle subclass of files

dessia_common/utils/serialization.py
=> fix(files): fix patch

dessia_common/breakdown.py, dessia_common/utils/serialization.py, dessia_common/utils/types.py, dessia_common/workflow/core.py
Throw Extraction error in case of sequence problem
=> fix: extraction error

dessia_common/workflow/blocks.py
Use pointers for workflow block to dict
=> fix: workflow block to dict with pointers

dessia_common/utils/diff.py
=> Fix:  utils/diff.py path 

CHANGELOG.md, code_pylint.py, dessia_common/breakdown.py, dessia_common/core.py, dessia_common/templates.py, dessia_common/tests.py, dessia_common/utils/copy.py, dessia_common/utils/diff.py, dessia_common/utils/serialization.py, dessia_common/utils/types.py, dessia_common/vectored_objects.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py, doc/source/customizing.rst
=> fix: foreachname configure not overriden anymore

dessia_common/breakdown.py
Catch error to get some traceback
=> debug: catch recursion error to show message

dessia_common/workflow/blocks.py
Handling static methods in classmethod workflow block
=> fix: handle static method as well as class methods

dessia_common/core.py, dessia_common/workflow/core.py
=> Fix: path for Input value in workflow state dict to object

dessia_common/displays.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> fix(wr): block Display now computes all object displays

dessia_common/workflow/blocks.py
=> Fix: to_dict method of Product block

dessia_common/forms.py
=> fix: change second prim with a cube

code_pylint.py, dessia_common/workflow/core.py, tests/workflow/workflow_with_models.py
=> fix(wr): get_from_path method now handles deep structures

dessia_common/exports.py
- [X ] Bug fix
- [ X] No
Problem in export xlsx with the conversion of cell into str
=> fix: export autosize for xlsx

setup.py
=> fix(setup): remove branch name

code_pylint.py, dessia_common/displays.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> fix(multiplot): return a DisplayObject with a sequenced data

dessia_common/forms.py, tests/workflow/forms_simulation.py, tests/workflow/workflow_with_models.py
=> test: uncomment check platform on workflow_runs now that it works

dessia_common/datatools.py
Nice export excel for categorizedlist: Label is printed in name for all dessia_objects so that the clusters information is not lost when exported.
Could be better if labels were written in a specific column but the class XLSWriter is not fit for it.
=> feat(clist_xls): Custom export to_xlsx_stream method for clist

dessia_common/workflow/core.py, tests/ci_tests.py, tests/workflow/workflow_building.py
=> Workflow metadata (name)

code_quality.sh, dessia_common/forms.py, tests/jsonschema.py
=> fix(forms): Wrong typing class was making the install fail

dessia_common/workflow/core.py
=> fix serialize bug : add serialize if default value

dessia_common/core.py, dessia_common/utils/jsonschema.py
=> fix(jsonschema): method

dessia_common/forms.py
=> feat: add function that counts and can raise an error

code_pylint.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py, tests/workflow/wokflow_displays_simulation.py
- Fixes CadView block type
- Add filename input to export blocks
- Add ConcatString block
- Handle streams with filename + extensions
=> Workflow & Blocks general fixes

setup.py
dependency on scikit learn declared in DC is not honored, this is breaking backend as it cause failed import of DC. I suggest this to be added as a patch as well.
=> fix: declare correct dependecy for sklearn

.drone.yml
=> ci: automated master -> testing testing -> dev

CHANGELOG.md, dessia_common/utils/diff.py, tests/ci_tests.py, tests/utils/diff.py
- Fix commutation when dicts are uneven
- Fix path deepth when missing keys
- Add tests over the two fixes
=> Fix some Diff Dict issues

dessia_common/utils/serialization.py, dessia_common/workflow/core.py
=> Feat for backend refacto

CHANGELOG.md, dessia_common/utils/diff.py, tests/ci_tests.py, tests/utils/diff.py
This reverts commit 963cfcc7f64ebc399cdc8398212c25a65df9ba0f, reversing changes made to 230f3ffaee01735fb694803cc080e032fd74ebaa.
See #429
=> Revert "Merge pull request #430 from Dessia-tech/fix/dev"

dessia_common/utils/jsonschema.py
=> fix(jsonschema): fix measures unit

dessia_common/core.py
=> PATCH : Add extension to xlsx if missing

code_pydocstyle.py, dessia_common/checks.py, dessia_common/core.py, dessia_common/displays.py, dessia_common/utils/serialization.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> doc: add for pydocstyle

CHANGELOG.md, dessia_common/optimization.py, dessia_common/workflow/core.py
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?):
Hot fix for ticket https://github.com/Dessia-tech/dessia_common/issues/477
=> fix(block_is_valid): hot fix return always true

CHANGELOG.md, code_pydocstyle.py
=> daily code_pydocstyle.py

dessia_common/utils/types.py
fix bug maximum recursion when calling Python object (quick fix)
=> Change recursion limit

CHANGELOG.md, README.md, setup.py
=> Upgrade to python3.8 minimum

dessia_common/workflow/blocks.py, tests/workflow/to_script.py
=> Merge master_fix_to_script into master

CHANGELOG.md, dessia_common/workflow/core.py, tests/workflow/workflow_method_dict.py
Fix bug ralated to serialize input if we put it default value
=> Serialize default value

CHANGELOG.md, code_pydocstyle.py, dessia_common/breakdown.py, dessia_common/checks.py, dessia_common/core.py, dessia_common/displays.py, dessia_common/files.py, dessia_common/forms.py, dessia_common/generation.py, dessia_common/measures.py, dessia_common/serialization.py, dessia_common/utils/copy.py, dessia_common/utils/docstrings.py, dessia_common/workflow/core.py
=> Pydocstyle 2(00), le retour.

CHANGELOG.md, setup.py
=> chore: empty commit

CHANGELOG.md, dessia_common/datatools/cluster.py, dessia_common/datatools/dataset.py, dessia_common/models/cars.py, dessia_common/models/power_test.py, dessia_common/models/rand_data.py, dessia_common/models/workflows/forms_workflow.py, dessia_common/models/workflows/power_simulation.py, dessia_common/models/workflows/wokflow_exports.py, dessia_common/models/workflows/workflow_from_file_input.py, dessia_common/optimization.py, dessia_common/serialization.py, dessia_common/tests.py, dessia_common/utils/docstrings.py, dessia_common/utils/serialization.py, dessia_common/workflow/blocks.py
=> (1) finish with docstyle rules

.drone.yml, CHANGELOG.md, tests/moving_object.py
CI: 
* upload coverage
* notify by email only on upstream fail
=> ci: upload coverage, notify by email only on merge fail

dessia_common/workflow/core.py
=> Merge fix_files_next into fix_files

.pyenchant_dessia.dict, CHANGELOG.md, dessia_common/core.py, dessia_common/datatools/cluster.py, dessia_common/datatools/dataset.py, dessia_common/forms.py, dessia_common/generation.py
=> 1 - Fix Spelling

CHANGELOG.md, code_pylint.py, dessia_common/abstract.py, dessia_common/checks.py, dessia_common/core.py, dessia_common/forms.py, dessia_common/schemas/core.py, dessia_common/utils/jsonschema.py, dessia_common/utils/types.py, tests/test_schemas/test_methods.py
=> 2 - Refactor Check Platform

CHANGELOG.md, code_pylint.py, dessia_common/checks.py, dessia_common/forms.py, dessia_common/schemas/core.py, dessia_common/utils/jsonschema.py, dessia_common/utils/types.py, tests/test_schemas/test_methods.py
=> 1 - Schemas low code improvements

CHANGELOG.md, dessia_common/core.py
=> fix: call hash instead of data hash

CHANGELOG.md, dessia_common/core.py
add stream type (jsonfile) to be able to use the function in the platform.
=> Merge dev_typing into dev

CHANGELOG.md, dessia_common/__init__.py, dessia_common/breakdown.py, dessia_common/serialization.py, dessia_common/workflow/core.py
=> fix: retrocompatibility for $ref

.pyenchant_dessia.dict, CHANGELOG.md, code_pylint.py, dessia_common/core.py, dessia_common/datatools/cluster.py, dessia_common/datatools/sampling.py, dessia_common/forms.py, dessia_common/optimization.py, dessia_common/schemas/core.py, dessia_common/serialization.py, dessia_common/tests.py, dessia_common/utils/diff.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> fix(global): spelling

dessia_common/core.py, dessia_common/document_generator.py, scripts/docx_writer.py
* **Other information**
Write markdown in docx file
=> feat/add from_markdown class method

.pyenchant_dessia.dict, CHANGELOG.md, dessia_common/core.py, dessia_common/serialization.py, dessia_common/typings.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py, scripts/docx_writer.py, scripts/models_test.py
use from_json and from_json_stream to download a dessiaobject from a file and a stream
https://github.com/Dessia-tech/dessia_common/issues/563
=> feat/rename load DessiaObject methods

CHANGELOG.md, LICENSE
=> LICENSE : from GPL to LGPL

CHANGELOG.md, dessia_common/workflow/core.py, test_unittests/workflow/test_to_script.py
=> fix: name wf if it has single quotes

CHANGELOG.md, dessia_common/core.py, dessia_common/workflow/core.py
=> Method Dict Backward Compat

CHANGELOG.md, dessia_common/__init__.py, dessia_common/core.py, dessia_common/displays.py, dessia_common/workflow/core.py, tests/test_workflow/test_displays.py
=> feat: hide documentation by default

CHANGELOG.md, dessia_common/core.py, dessia_common/forms.py, dessia_common/utils/types.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> Fix progress callback

code_pylint.py, dessia_common/core.py, dessia_common/decorators.py, dessia_common/forms.py, tests/test_workflow/test_displays.py
=> fix(decorators): get decorators from parent classes

CHANGELOG.md, code_pylint.py, dessia_common/serialization.py, dessia_common/workflow/blocks.py, dessia_common/workflow/core.py
=> chore: block backward compatibility

CHANGELOG.md, dessia_common/schemas/core.py, setup.py
=> fix(pylint): use iterator

CHANGELOG.md, setup.py
=> chore(setup): fix conflicts

CHANGELOG.md, dessia_common/decorators.py, dessia_common/forms.py, tests/test_displays/test_decorators.py
=> fix(decorator): use right type for cad decorator

CHANGELOG.md, dessia_common/forms.py
=> update: forms

CHANGELOG.md, dessia_common/models/cars.py, dessia_common/workflow/core.py, scripts/ci_scripts.py, scripts/workflow/workflow_building.py, scripts/workflow/workflow_clustering.py, scripts/workflow/workflow_filtering.py, scripts/workflow/workflow_pareto.py
=> feat(variable): add label

CHANGELOG.md, dessia_common/workflow/core.py
=> fix(workflow): make last hotfix work with more types

CHANGELOG.md, dessia_common/workflow/core.py
=> Patch 0.15.3 : Variable backward compatibility

CHANGELOG.md, dessia_common/core.py
=> mutualise step export

.drone.yml, CHANGELOG.md, coverage.py, dessia_common/serialization.py
=> fix: ref path

coverage.py
=> chore(drone): try and remove a coverage untracked file

CHANGELOG.md, dessia_common/workflow/blocks.py
=> Fix: Call right dict_to_object

CHANGELOG.md, tests/test_schemas/test_get_import_names.py
=> Unit test schema

CHANGELOG.md, dessia_common/workflow/blocks.py, tests/test_workflow/test_to_script.py
=> Fix: MultiPlot to_script/add missed selector_name

CHANGELOG.md, dessia_common/workflow/core.py, tests/test_workflow/test_displays.py
=> Fix: use markdown of workflowrun

CHANGELOG.md, dessia_common/core.py, dessia_common/decorators.py, tests/test_workflow/test_exports.py
=> Feat: Export/decorator

CHANGELOG.md, dessia_common/workflow/core.py
=> Fix: workflow markdown/before memory instead of after

CHANGELOG.md, setup.py
=> build(numpy): force version lower to 2.0.0

CHANGELOG.md, coverage.py, setup.py
=> chore(coverage): remove warnings from tracked modules

dessia_common/core.py, dessia_common/decorators.py, dessia_common/typings.py, dessia_common/utils/types.py
=> Picture decorator

CHANGELOG.md, dessia_common/files.py
=> feat(files): set filename in from_file method

CHANGELOG.md, dessia_common/workflow/blocks.py
=> feat(multi-object): sample names

CHANGELOG.md, dessia_common/forms.py, dessia_common/serialization.py
=> fix: deserialize literals

CHANGELOG.md, dessia_common/workflow/blocks.py
=> feat(workflow): export MultiObject to py

CHANGELOG.md, dessia_common/workflow/blocks.py
Untyped sequence blocks output until we don't have a way to propagate types
=> Fix: sequence typing

CHANGELOG.md, dessia_common/workflow/core.py, tests/test_schemas/test_workflows.py
=> chore: deprecate start_run

CHANGELOG.md, dessia_common/schemas/core.py, dessia_common/workflow/core.py
=> feat(wizard): add id to steps

CHANGELOG.md, dessia_common/serialization.py, dessia_common/utils/types.py, tests/test_serialization/test_classes.py
=> Deserialize strings that start with "." as str instead of class
